name: acs-plots
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - scipy
  - contextily
  - jupyterlab
  - notebook
  - nbconvert
  - myst-parser
  - pytest
  - statsmodels
  - openpyxl
  - pip
  - pip:
    - myst-nb
